### ISSUE TITLE
Uncaught `None` passed to `create_symlinks()` causes crash

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/auto-fastq-symlink#18]
We've had a crash with the following error message:

```
Traceback (most recent call last):
  File "/path/to/auto-fastq-symlink/bin/auto-fastq-symlink", line 33, in <module>
    sys.exit(load_entry_point('auto-fastq-symlink', 'console_scripts', 'auto-fastq-symlink')())
  File "/path/to/auto-fastq-symlink/auto_fastq_symlink/__main__.py", line 57, in main
    core.symlink_run(config, run)
  File "/path/to/auto-fastq-symlink/auto_fastq_symlink/core.py", line 463, in symlink_run
    symlinks_complete_by_project_id = create_symlinks(config, symlinks_to_create, run_id)
  File "/path/to/auto-fastq-symlink/auto_fastq_symlink/core.py", line 363, in create_symlinks
    target_basename = os.path.basename(symlink['target'])
  File "/path/to/auto-fastq-symlink/lib/python3.10/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

...suggesting that a `None` value slipped through to the `create_symlinks()` method, and we attempted to get its basename, causeing a `TypeError` to be thrown.

**Comment by dfornika** [comment]
Error appears to be occurring here:

https://github.com/BCCDC-PHL/auto-fastq-symlink/blob/bdf125fa06054aab69fe40f39b569bfc22b056e6/auto_fastq_symlink/core.py#L363

...because the value of `symlink['target']` is `None`.
